/**
 * July 2026 EU Registry — machine-readable batch package (JSON-LD + CSV helpers).
 */
import type { BatchExportData, MaterialCompositionEntry } from "@/lib/dpp-export"

function normalizedMaterials(data: BatchExportData): MaterialCompositionEntry[] {
  const { batch, product } = data
  if (Array.isArray(batch.material_composition) && batch.material_composition.length > 0) {
    return batch.material_composition
  }
  if (product.materials?.trim()) {
    return [{ material: product.materials.trim(), percentage: 100 }]
  }
  return []
}

/**
 * Single consolidated JSON-LD document (@graph) for customs / registry ingestion.
 */
export function buildConsolidatedBatchJsonLd(
  data: BatchExportData,
  baseUrl: string,
  exportDate: Date
): Record<string, unknown> {
  const base = baseUrl.replace(/\/$/, "")
  const batchUri = `${base}#batch-${data.batch.id}`
  const brandUri = `${base}#brand-${data.brand.id}`
  const brandName = data.brand.brand_name || "Unknown Brand"
  const materials = normalizedMaterials(data)

  const materialRows = materials.map((m) => ({
    "@type": "PropertyValue",
    name: m.material,
    value: m.percentage,
    unitText: "percent",
  }))

  const graph: Record<string, unknown>[] = [
    {
      "@id": brandUri,
      "@type": "Brand",
      name: brandName,
    },
    {
      "@id": batchUri,
      "@type": ["Product", "DigitalProductPassport"],
      name: data.product.name,
      identifier: data.batch.id,
      sku: data.batch.production_run_name ?? undefined,
      description: data.product.story ?? undefined,
      brand: { "@id": brandUri },
      manufacturer: {
        "@type": "Organization",
        name: data.batch.artisan_name || brandName,
        location: data.batch.location ?? undefined,
      },
      additionalProperty: [
        ...materialRows,
        {
          "@type": "PropertyValue",
          name: "facilityIdentifier",
          value: data.batch.facility_info || data.batch.location || data.batch.artisan_name || "",
        },
        {
          "@type": "PropertyValue",
          name: "euRegistryComplianceNote",
          value: "Machine-readable DPP export for EU ESPR / July 2026 registry expectations",
        },
        {
          "@type": "PropertyValue",
          name: "exportGeneratedAt",
          value: exportDate.toISOString(),
        },
      ],
      productionDate: data.batch.produced_at
        ? new Date(data.batch.produced_at).toISOString().split("T")[0]
        : undefined,
    },
    {
      "@id": `${batchUri}/serials`,
      "@type": "ItemList",
      numberOfItems: data.items.length,
      itemListElement: data.items.map((item, i) => ({
        "@type": "ListItem",
        position: i + 1,
        item: {
          "@type": "Product",
          "@id": `${base}/verify/${item.serial_id}`,
          name: data.product.name,
          serialNumber: item.serial_id,
          url: `${base}/verify/${item.serial_id}`,
        },
      })),
    },
  ]

  return {
    "@context": [
      "https://schema.org",
      "https://ref.gs1.org/standards/gs1-digital-link",
    ],
    "@graph": graph,
  }
}

export function buildMaterialsCsv(data: BatchExportData): string {
  const rows: MaterialCompositionEntry[] = normalizedMaterials(data)
  const header = "component,percentage,source\n"
  if (rows.length === 0) {
    return header + '"",,"no_material_data"\n'
  }
  const source =
    Array.isArray(data.batch.material_composition) && data.batch.material_composition.length > 0
      ? "batch_material_composition"
      : "product_materials_fallback"
  const lines = rows.map((r) => {
    const comp = `"${String(r.material).replace(/"/g, '""')}"`
    const pct = Number.isFinite(r.percentage) ? String(r.percentage) : ""
    return `${comp},${pct},${source}`
  })
  return header + lines.join("\n") + "\n"
}

export const COMPLIANCE_PACKAGE_README = `ORIGINPASS — COMPLIANCE PACKAGE (JULY 2026 EU REGISTRY)
=====================================================

OriginPass: One-click compliance for the July 2026 EU Registry.

CONTENTS
--------
1. eu-registry/batch-dpp.jsonld
   Machine-readable JSON-LD (@graph) for the batch, brand, and serial list with verification URLs.

2. materials/material-components.csv
   Tabular material components (percentages and data source).

3. certificate/originality-certificate.pdf
   Customer-facing originality certificate.

REGISTRY USE
------------
Authorities increasingly require structured data (JSON / XML), not PDF alone. Submit the .jsonld
and CSV with customs; use the PDF as a human-readable supplement.

Generated by OriginPass.
`
