/**
 * EU Regulatory / Compliance Data Export
 * Maps internal batch data to GS1 Digital Link JSON-LD for EU customs and market surveillance.
 * Uses https://gs1.github.io/Product-Data-Definitions/context.jsonld
 */

export interface RegulatoryExportBatchData {
  batch: {
    id: string
    production_run_name: string | null
    artisan_name: string | null
    location: string | null
    produced_at: string | null
    material_composition: { material: string; percentage: number }[] | null
    maintenance_instructions: string | null
    end_of_life_instructions: string | null
    facility_info: string | null
  }
  product: {
    id: string
    name: string
    story: string | null
    materials: string | null
    origin: string | null
    lifecycle: string | null
    image_url: string | null
  }
  brand: {
    id: string
    brand_name: string | null
  }
  items: Array<{
    id: string
    serial_id: string
  }>
  baseUrl: string
}

export interface RegulatoryJsonLd {
  "@context": string
  "@type": string
  id: string
  name: string
  brand: {
    name: string
    location?: string
  }
  composition: string[]
  circularity: {
    repairInstructions?: string
    endOfLifeInstructions?: string
  }
  facility: string
  productOrigin?: string
  productionDate?: string
  image?: string
}

/**
 * Maps internal batch data to EU-compliant JSON-LD using GS1 structure.
 * Essential fields for 2026 ESPR.
 */
export function mapToRegulatoryJsonLd(
  item: { id: string; serial_id: string },
  data: RegulatoryExportBatchData
): RegulatoryJsonLd {
  const { batch, product, brand, baseUrl } = data

  // id: Unique GS1 Digital Link URI for the product
  const id = `${baseUrl.replace(/\/$/, "")}/verify/${item.serial_id}`

  // brand: Artisan's brand name and location
  const brandName = brand.brand_name || "Unknown Brand"
  const brandLocation = batch.location || product.origin || undefined

  // composition: Array of materials (e.g., "95% Organic Wool, 5% Plant Dye")
  const composition: string[] =
    Array.isArray(batch.material_composition) && batch.material_composition.length > 0
      ? batch.material_composition.map(
          (m) => `${m.percentage}% ${m.material}`.trim()
        )
      : product.materials
        ? [product.materials]
        : []

  // circularity: Repair guides and end-of-life recycling instructions
  const circularity = {
    repairInstructions: batch.maintenance_instructions || undefined,
    endOfLifeInstructions: batch.end_of_life_instructions || undefined,
  }

  // facility: GPS coordinates or Address of the workshop
  const facility =
    batch.facility_info || batch.location || batch.artisan_name || "Unknown facility"

  return {
    "@context": "https://gs1.github.io/Product-Data-Definitions/context.jsonld",
    "@type": "Product",
    id,
    name: product.name,
    brand: {
      name: brandName,
      ...(brandLocation && { location: brandLocation }),
    },
    composition,
    circularity,
    facility,
    productOrigin: product.origin || undefined,
    productionDate: batch.produced_at
      ? new Date(batch.produced_at).toISOString().split("T")[0]
      : undefined,
    image: product.image_url || undefined,
  }
}

export const REGULATORY_README = `ORIGINPASS REGULATORY EXPORT
============================

This ZIP contains EU-compliant, machine-readable product data for your batch.

CONTENTS
--------
- One .jsonld file per product item (serial number)
- Each file uses the GS1 Digital Link URI structure
- Format: JSON-LD with schema.org vocabularies extended for Digital Product Passport (DPP)

HOW TO USE
----------
1. Present these files to EU customs or market surveillance authorities when requested
2. The data is interoperable and can be validated against EU ESPR 2026 requirements
3. Each file contains: unique product ID, brand, material composition, circularity info, and facility details

STANDARDS
---------
- @context: https://gs1.github.io/Product-Data-Definitions/context.jsonld
- EU Ecodesign for Sustainable Products Regulation (ESPR) 2026
- GS1 Digital Link URI for traceability

Generated by OriginPass. Your data remains portable and audit-ready.
`
