import React, { forwardRef } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { ShieldCheck } from 'lucide-react';

interface PrintLabelsProps {
    codes: { serialId: string }[];
    baseUrl: string;
    className?: string;
}

export const PrintLabels = forwardRef<HTMLDivElement, PrintLabelsProps>(({ codes, baseUrl, className }, ref) => {
    return (
        <div className={`hidden print:block print:w-full ${className || ''}`} ref={ref}>
            <style type="text/css" media="print">
                {`
                    @page {
                        size: auto;
                        margin: 10mm;
                    }
                    body {
                        print-color-adjust: exact;
                        -webkit-print-color-adjust: exact;
                    }
                `}
            </style>

            <div className="grid grid-cols-3 gap-4 p-4">
                {codes.map((code) => (
                    <div
                        key={code.serialId}
                        className="border border-slate-900 rounded-lg p-4 flex flex-col items-center justify-center text-center space-y-2 break-inside-avoid page-break-inside-avoid h-[200px]"
                    >
                        {/* Header */}
                        <div className="flex items-center gap-1.5 mb-1">
                            <ShieldCheck className="w-4 h-4 text-slate-900" />
                            <span className="font-bold text-slate-900 text-xs tracking-tight">OriginPass</span>
                        </div>

                        {/* QR Code */}
                        <div className="bg-white p-1">
                            <QRCodeSVG
                                value={`${baseUrl}/verify/${code.serialId}`}
                                size={96} // Approx 1 inch / 2.5cm
                                level="M"
                                includeMargin={false}
                            />
                        </div>

                        {/* Footer */}
                        <div>
                            <p className="text-[10px] font-mono font-bold text-slate-900 uppercase tracking-widest leading-none mt-1">
                                {code.serialId}
                            </p>
                            <p className="text-[8px] text-slate-500 uppercase tracking-wide mt-1">
                                Scan to Verify
                            </p>
                        </div>
                    </div>
                ))}
            </div>

            {/* Print Footer Metada */}
            <div className="fixed bottom-0 left-0 w-full text-center text-[10px] text-slate-400 mt-8">
                Generated by OriginPass • {new Date().toLocaleDateString()}
            </div>
        </div>
    );
});

PrintLabels.displayName = 'PrintLabels';
